### ISSUE TITLE
Target temperature changes to 70 (default is 60)

### ISSUE THREAD

**Issue by tashgitt** [Schnitzel/hass-miner#249]
Somehow Target temperature changes from 60 to 70 when I use HA's automation service:

![image](https://github.com/Schnitzel/hass-miner/assets/131814300/ec36344e-d881-49d4-8e8d-012e8622a558)

The weird part is that it doesn't happen all the time. If you tell me which logs to get you (BOS+ and/or HA) I can post them here when it happens. When I used Braiins toolbox to change power limit on all clients the target temp wouldn't change. To be fair - I like it better when target temperature is set to 70, because the fans are quieter (understandingly), but I feel uneasy that something changed without a reason. Also not sure if S19J are ok to work at 70C.
## Configuration
I want to use preset values to switch all miners' power limit to i.e. 1700, 2200, 3000. So I have a dropdown helper "MaxPL" and then an automation that is being triggered on MaxPL's state change and MaxPL's value is passed to action (a service call for each miner). 
```yaml
alias: MaxPL SHIP
description: ""
trigger:
  - platform: state
    entity_id:
      - input_select.maxpl_ship_dropdown
condition: []
action:
  - service: number.set_value
    data:
      value: "{{ trigger.to_state.state }}"
    target:
      entity_id: number.2x50_power_limit
  - service: number.set_value
    data:
      value: "{{ trigger.to_state.state }}"
    target:
      entity_id: number.2x81_power_limit
mode: single
```
