### ISSUE TITLE
When Miner goes offline, make HA set it's values in dashboard to  Zero 

### ISSUE THREAD

**Issue by mannebk79** [Schnitzel/hass-miner#392]
So, I have a machine that I pull the plug.on simple as that... And the HA dashboard shows last values until it goes back online....

Stock Antminer S19 I use for heating my shed when I want it warm, cause they won't make money on German electricity costs. So I would like to know it's on or off from the dashboard, no sense in heating an empty shed and wasting money.

What am I doing wrong here?

![Screenshot_20241001-110016](https://github.com/user-attachments/assets/4da270fb-b8ff-4f07-9507-165c6fca9587)

The read one is only on when I need my shed warm...
Better get some money back than just use a space heater.

Thanks

**Comment by b-rowan** [comment]
What does your config look like for that card?  Usually ApexCharts will skip over null values, resulting in a gap in your graph (which is more likely what you would want, offline is different than 0 hashrate).

**Comment by mannebk79** [comment]
Hi 

My yaml looks like this.

I currently don't have a sample but it literally describes a curve down to zero ant the next available data point.

```
type: custom:apexcharts-card
:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.30_hashrate
  - entity: sensor.31_hashrate
  - entity: sensor.32_hashrate

```

Thank's 
Manny

Am 2. Oktober 2024 14:20:16 UTC schrieb Brett Rowan ***@***.***>:

**Comment by b-rowan** [comment]
Try this - 

From the docs, this should set missing values to 0.  The default is `null`, but  I don't think that's working properly.

```yaml
# ... skipping some config
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.30_hashrate
  - entity: sensor.31_hashrate
  - entity: sensor.32_hashrate
all_series_config:
  fill_raw: "zero"
```
