### ISSUE TITLE
Avalon Nano 3S commands?

### ISSUE THREAD

**Issue by DarKOrange75** [Schnitzel/hass-miner#535]
Hi, 

Is it possible to do something else than rebooting or reloading the Nano 3S from Home Assistant?
Is is possible to changer working mode?

Thank you.

**Comment by hugochar** [comment]
Hi Guys it's in french, but a guy make it working and it works for me, follow the steps :)

here is the link 

https://www.reddit.com/r/BitcoinMining/comments/1k9cdql/how_to_change_mining_modes_depending_on_time/


You need visual studio code to makes modifications

Dans /config/custom_components/miner/const.py, ajoute :

`SERVICE_SET_WORK_MODE = "set_work_mode"`

Dans /config/custom_components/miner/device_action.py

Ajoute les imports :

`from .const import SERVICE_SET_WORK_MODE`

Ajoute "set_work_mode" à la variable ACTION_TYPES existante :

`ACTION_TYPES = {"reboot", "restart_backend", "set_work_mode"}`

Ajoute le gestionnaire d'action à la méthode async_call_action_from_config comme partie des vérifications if existantes :


```
    elif config[CONF_TYPE] == "set_work_mode":
        service = SERVICE_SET_WORK_MODE
```

Dans /config/custom_components/miner/services.py

Ajoute les imports :

`from .const import SERVICE_SET_WORK_MODE`


En bas du fichier, ajoute le gestionnaire de méthode :


```
async def set_work_mode(call: ServiceCall) -> None:
        miners = await get_miners(call)
        if len(miners) > 0:
            mode = call.data["mode"]
            modeNum = 2 # default to high
            if mode == "low":
                modeNum = 0
            elif mode == "medium":
                modeNum = 1
            await asyncio.gather(*[miner.rpc.ascset(0, "workmode", f"set,{modeNum}") for miner in miners])

    hass.services.async_register(DOMAIN, SERVICE_SET_WORK_MODE, set_work_mode)
```

Dans /config/custom_components/miner/services.yaml, ajoute :

```
set_work_mode:
  target:
    device:
      integration: miner
  fields:
    mode:
      required: true
      example: "low"
      default: "high"
      selector:
        select:
          options:
            - "low"
            - "medium"
            - "high"

```
